In [2]:
import pandas as pd

In [11]:
df = pd.read_csv('Movie_Data (1).csv')
df

       title     genre  rating  release_year  box_office
0    Movie 1     Drama     3.5          2017  1203441917
1    Movie 2     Drama     4.5          2010   635116663
2    Movie 3  Thriller     5.8          2019  1541264226
3    Movie 4     Drama     8.6          2003   735554784
4    Movie 5    Comedy     6.3          2014  1396345053
5    Movie 6  Thriller     6.3          2021   252903032
6    Movie 7  Thriller     2.2          2000  1353524786
7    Movie 8     Drama     4.3          2012   604070646
8    Movie 9  Thriller     4.6          2017   375364664
9   Movie 10  Thriller     2.0          2003  1697296851
10  Movie 11    Comedy     9.0          2018  1956641510
11  Movie 12    Horror     9.6          2003   681020606
12  Movie 13    Action     3.3          2023   291472802
13  Movie 14    Action     9.1          2009   540243881
14  Movie 15    Comedy     2.8          2023   134909247
15  Movie 16    Comedy     3.5          2014   292905192
16  Movie 17  Thriller     7.8          2020  1909403222
17  Movie 18    Comedy     5.9          2023  1751052319
18  Movie 19    Comedy     3.5          2018   958875818
19  Movie 20    Horror     1.2          2018  1971919840
20  Movie 21    Action     1.4          2022  1930454283
21  Movie 22    Comedy     5.6          2011  1650948235
22  Movie 23    Action     5.7          2015  1455147571
23  Movie 24    Comedy     6.5          2023  1831436334
24  Movie 25    Comedy     4.4          2002  1469061887
25  Movie 26    Action     9.2          2018  1884776336
26  Movie 27  Thriller     1.7          2009  1132120249
27  Movie 28    Comedy     2.5          2002   326956878
28  Movie 29     Drama     1.4          2017   203500137
29  Movie 30    Horror     3.5          2004  1883738397
30  Movie 31  Thriller     9.3          2003  1163312251
31  Movie 32  Thriller     6.5          2014   281815830
32  Movie 33    Horror     6.2          2013  1283113566
33  Movie 34     Drama     4.3          2009  1424174623
34  Movie 35    Comedy     8.7          2007   634403854
35  Movie 36    Action     8.2          2000  1282931288
36  Movie 37    Horror     8.8          2003  1422968393
37  Movie 38    Horror     4.8          2016   699586660
38  Movie 39  Thriller     2.0          2006   610725053
39  Movie 40    Action     8.5          2010   402972563
40  Movie 41    Action     6.9          2002  1340542615
41  Movie 42     Drama     3.7          2000  1234594283
42  Movie 43    Horror     4.0          2011  1325723984
43  Movie 44    Action     7.6          2016  1919952302
44  Movie 45    Comedy     9.2          2005  1138648654
45  Movie 46    Action     4.8          2007  1344151579
46  Movie 47     Drama     5.3          2017  1926080840
47  Movie 48     Drama     9.3          2013  1776382539
48  Movie 49    Horror     8.6          2002   885975587
49  Movie 50     Drama     7.1          2023  1376039520

Task 1

In [60]:
highest_box_office = df['box_office'].max()
top_movie = df[df['box_office'] == highest_box_office]
print(top_movie[['title', 'genre','rating','release_year']])

Average_rating = df['rating'].mean()
print('\nAverage_rating:',Average_rating)

Median = df['release_year'].max(),  df['genre'].mode()
print('\nMedian and mode:',Median)

       title   genre  rating  release_year
19  Movie 20  Horror     1.2          2018

Average_rating: 5.590000000000001

Median and mode: (2023, 0    Comedy
Name: genre, dtype: object)

Task 2

In [56]:
Rating = df.loc[df['rating']>7]
print("Rating")
print(Rating)

top_10_box_office = df.sort_values(by='box_office', ascending=False).head(10)
print("\nTop 10 box office")
print(top_10_box_office)

df['Profitability'] = df['box_office']/100_000_000
print('\nProfitability')
print(df[['title', 'box_office', 'Profitability']])

Rating
       title     genre  rating  release_year  box_office  Profitability
3    Movie 4     Drama     8.6          2003   735554784       7.355548
10  Movie 11    Comedy     9.0          2018  1956641510      19.566415
11  Movie 12    Horror     9.6          2003   681020606       6.810206
13  Movie 14    Action     9.1          2009   540243881       5.402439
16  Movie 17  Thriller     7.8          2020  1909403222      19.094032
25  Movie 26    Action     9.2          2018  1884776336      18.847763
30  Movie 31  Thriller     9.3          2003  1163312251      11.633123
34  Movie 35    Comedy     8.7          2007   634403854       6.344039
35  Movie 36    Action     8.2          2000  1282931288      12.829313
36  Movie 37    Horror     8.8          2003  1422968393      14.229684
39  Movie 40    Action     8.5          2010   402972563       4.029726
43  Movie 44    Action     7.6          2016  1919952302      19.199523
44  Movie 45    Comedy     9.2          2005  1138648654      11.386487
47  Movie 48     Drama     9.3          2013  1776382539      17.763825
48  Movie 49    Horror     8.6          2002   885975587       8.859756
49  Movie 50     Drama     7.1          2023  1376039520      13.760395

Top 10 box office
       title     genre  rating  release_year  box_office  Profitability
19  Movie 20    Horror     1.2          2018  1971919840      19.719198
10  Movie 11    Comedy     9.0          2018  1956641510      19.566415
20  Movie 21    Action     1.4          2022  1930454283      19.304543
46  Movie 47     Drama     5.3          2017  1926080840      19.260808
43  Movie 44    Action     7.6          2016  1919952302      19.199523
16  Movie 17  Thriller     7.8          2020  1909403222      19.094032
25  Movie 26    Action     9.2          2018  1884776336      18.847763
29  Movie 30    Horror     3.5          2004  1883738397      18.837384
23  Movie 24    Comedy     6.5          2023  1831436334      18.314363
47  Movie 48     Drama     9.3          2013  1776382539      17.763825

Profitability
       title  box_office  Profitability
0    Movie 1  1203441917      12.034419
1    Movie 2   635116663       6.351167
2    Movie 3  1541264226      15.412642
3    Movie 4   735554784       7.355548
4    Movie 5  1396345053      13.963451
5    Movie 6   252903032       2.529030
6    Movie 7  1353524786      13.535248
7    Movie 8   604070646       6.040706
8    Movie 9   375364664       3.753647
9   Movie 10  1697296851      16.972969
10  Movie 11  1956641510      19.566415
11  Movie 12   681020606       6.810206
12  Movie 13   291472802       2.914728
13  Movie 14   540243881       5.402439
14  Movie 15   134909247       1.349092
15  Movie 16   292905192       2.929052
16  Movie 17  1909403222      19.094032
17  Movie 18  1751052319      17.510523
18  Movie 19   958875818       9.588758
19  Movie 20  1971919840      19.719198
20  Movie 21  1930454283      19.304543
21  Movie 22  1650948235      16.509482
22  Movie 23  1455147571      14.551476
23  Movie 24  1831436334      18.314363
24  Movie 25  1469061887      14.690619
25  Movie 26  1884776336      18.847763
26  Movie 27  1132120249      11.321202
27  Movie 28   326956878       3.269569
28  Movie 29   203500137       2.035001
29  Movie 30  1883738397      18.837384
30  Movie 31  1163312251      11.633123
31  Movie 32   281815830       2.818158
32  Movie 33  1283113566      12.831136
33  Movie 34  1424174623      14.241746
34  Movie 35   634403854       6.344039
35  Movie 36  1282931288      12.829313
36  Movie 37  1422968393      14.229684
37  Movie 38   699586660       6.995867
38  Movie 39   610725053       6.107251
39  Movie 40   402972563       4.029726
40  Movie 41  1340542615      13.405426
41  Movie 42  1234594283      12.345943
42  Movie 43  1325723984      13.257240
43  Movie 44  1919952302      19.199523
44  Movie 45  1138648654      11.386487
45  Movie 46  1344151579      13.441516
46  Movie 47  1926080840      19.260808
47  Movie 48  1776382539      17.763825
48  Movie 49   885975587       8.859756
49  Movie 50  1376039520      13.760395

Task 3

In [61]:
df.groupby('genre')[['rating','box_office']].mean()

            rating    box_office
genre
Action    6.470000  1.239265e+09
Comedy    5.658333  1.128515e+09
Drama     5.200000  1.111896e+09
Horror    5.837500  1.269256e+09
Thriller  4.820000  1.031773e+09